### ISSUE TITLE
ModuleNotFoundError: No module named 'oimOptions'

### ISSUE THREAD

**Issue by pboley** [oimodeler/oimodeler#14]
Now after installing latest commits through setup.py, the oimodeler module no longer imports.

```python
>>> import oimodeler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/miniconda3/lib/python3.10/site-packages/oimodeler-0.1-py3.10.egg/oimodeler/__init__.py", line 8, in <module>
ModuleNotFoundError: No module named 'oimOptions'
```

I compared with an earlier commit which worked (e.g. a5d01831ab6b54822f5562081ada122bea063724) and
```python
from .oimOptions import oimOptions
```
became
```python
from oimOptions import oimOptions
```
(along with all other modules).

**Comment by MBSck** [comment]
The same error occurs for me...

As Paul mentioned, if you change all absolute imports in the `__init__.py`-file of the `oimodeler` package to realtive imports, the imports work as anticipated. (I would also generally advise to change all the imports in the package to relative, instead of absolute to avoid errors in the long run, as done/shown by me in Pull request #11 albeit it is a bit outdated now)

However, there is another error, if this is corrected  as described above (I have also changed the line `import oimCustomComponents as oimCustomComponents` to `from .oimCustomComponents import *`) then this occurs:
```
Traceback (most recent call last):
  File "/Users/scheuck/Code/modelling/test.py", line 3, in <module>
    import oimodeler as oim
  File "/Users/scheuck/Code/modelling/oimodeler/oimodeler/__init__.py", line 15, in <module>
    from .oimCustomComponents import *
  File "/Users/scheuck/Code/modelling/oimodeler/oimodeler/oimCustomComponents/__init__.py", line 20, in <module>
    from .oimFastRotator import oimFastRotator
  File "/Users/scheuck/Code/modelling/oimodeler/oimodeler/oimCustomComponents/oimFastRotator.py", line 10, in <module>
    from fastRotator import fastRotator
ModuleNotFoundError: No module named 'fastRotator'
```
Is there maybe a python package called `fastRotator` not included in the `setup.py`?
