### ISSUE TITLE
`Attribute Error`: `oimConvolutor` object has no attribute `getFreeParameters`

### ISSUE THREAD

**Issue by MBSck** [oimodeler/oimodeler#24]
This appears when one uses the `oimConvolutor`-class
```python3
Traceback (most recent call last):
  File "/Users/scheuck/Code/modelling/ring_gauss_convolution.py", line 60, in <module>
    main(fits_file)
  File "/Users/scheuck/Code/modelling/ring_gauss_convolution.py", line 34, in main
    sim = oim.oimSimulator(data=files, model=model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scheuck/Code/modelling/oimodeler/oimodeler/oimSimulator.py", line 83, in __init__
    self.compute(computeChi2=True,computeSimulatedData=True)
  File "/Users/scheuck/Code/modelling/oimodeler/oimodeler/oimSimulator.py", line 206, in compute
    self.chi2r=chi2/(nelChi2-len(self.model.getFreeParameters()))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'oimConvolutor' object has no attribute 'getFreeParameters'
```

**Comment by MBSck** [comment]
Wrong usage of `oimConvolutor`
