### ISSUE TITLE
oimSimulator issue with files containing only one wavelength

### ISSUE THREAD

**Issue by jdrevon** [oimodeler/oimodeler#4]
Hi Anthony,

It seems that when I want to use a concatenated file (from OIFITs Explorer for example) including only one wavelength, the code generates an error:

The error occurs when running this command line:

sim=oim.oimSimulator(data=files,model=model)

Cheers

Julien

```

{'c1_UD_d': oimParam at 0x1334cefe4f0 : d=43 ± 0 mas range=[10,60] free=True }
Traceback (most recent call last):

  File "C:\Users\jdrevon\Desktop\OIMODELER\main.py", line 25, in <module>
    sim=oim.oimSimulator(data=files,model=model)

  File "C:\Users\jdrevon\anaconda3\lib\site-packages\oimodeler\oimSimulator.py", line 85, in __init__
    self.compute(computeChi2=True,computeSimulatedData=True)

  File "C:\Users\jdrevon\anaconda3\lib\site-packages\oimodeler\oimSimulator.py", line 182, in compute
    self.simulatedData.data[ifile][arrNum].data[quantities[ival]]=val[ival]

  File "C:\Users\jdrevon\anaconda3\lib\site-packages\astropy\io\fits\fitsrec.py", line 540, in __setitem__
    self[key][:] = value

ValueError: could not broadcast input array from shape (24,1) into shape (24,)
```

**Comment by AnthonyMeilland** [comment]
You are diabolical :-)

Can you send me such an demoniac oifits file by email so that I can reproduce the error?
It shouldn't be complicated to correct (just reshaping the array if there's only one baseline)
But there're probably the same errors in other part of the code.
