### ISSUE TITLE
[Bug] `exampleOimPlot` small error

### ISSUE THREAD

**Issue by MBSck** [oimodeler/oimodeler#61]
**Describe the bug**
The line 124 `fig.autoShape(data.data,shape=[["VIS2DATA",None],["VISPHI","T3PHI"]])` in `exampleOimPlot` gives the error:
```python
  File "/Users/scheuck/Code/modelling/oimodeler/examples/BasicExamples/exampleOimPlot.py", line 124, in <module>
    fig.autoShape(data.data,shape=[["VIS2DATA",None],["VISPHI","T3PHI"]])
  File "/Users/scheuck/Code/modelling/oimodeler/oimodeler/oimPlots.py", line 820, in autoShape
    self.axes[0].get_shared_x_axes().join(self.axes[0], *self.axes[1:])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GrouperView' object has no attribute 'join'. Did you mean: 'joined'?
```
But even if `joined` is substituted it yields another error
```python3
Traceback (most recent call last):
  File "/Users/scheuck/Code/modelling/oimodeler/examples/BasicExamples/exampleOimPlot.py", line 124, in <module>
    fig.autoShape(data.data,shape=[["VIS2DATA",None],["VISPHI","T3PHI"]])
  File "/Users/scheuck/Code/modelling/oimodeler/oimodeler/oimPlots.py", line 820, in autoShape
    self.axes[0].get_shared_x_axes().joined(self.axes[0], *self.axes[1:])
TypeError: GrouperView.joined() takes 3 positional arguments but 17 were given
```

**Comment by MBSck** [comment]
Solved with commit (92d5fb4)[https://github.com/oimodeler/oimodeler/commit/92d5fb45438c45466620e6ed04845bee6a59be8b]
