### ISSUE TITLE
`numpy.asscalar` is depracated

### ISSUE THREAD

**Issue by MBSck** [oimodeler/oimodeler#8]
I have just gotten informed by email that there is a small deprecation error in the code:

The function [`numpy.asscalar`](https://numpy.org/doc/1.22/reference/generated/numpy.asscalar.html) is deprecated since version 1.16 of numpy and should be exchanged.
> Deprecated since version 1.16: Deprecated, use `numpy.ndarray.item()` instead.

The corresponding error:
```
bash-5.1$ python3
Python 3.9.13 (main, May 18 2022, 00:00:00)
[GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import oimodeler as oim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/home/aoplisti/ESO/oimodeler-main/oimodeler/__init__.py", line 10, in <module>
    from .oimParam import *
  File "/scratch/home/aoplisti/ESO/oimodeler-main/oimodeler/oimParam.py", line 9, in <module>
    from astropy import units as units
  File "/usr/lib64/python3.9/site-packages/astropy/units/__init__.py", line 17, in <module>
    from .quantity import *
  File "/usr/lib64/python3.9/site-packages/astropy/units/quantity.py", line 28, in <module>
    from .quantity_helper import (converters_and_unit, can_have_arbitrary_unit,
  File "/usr/lib64/python3.9/site-packages/astropy/units/quantity_helper/__init__.py", line 10, in <module>
    from . import helpers, function_helpers
  File "/usr/lib64/python3.9/site-packages/astropy/units/quantity_helper/function_helpers.py", line 119, in <module>
    np.asscalar,
  File "/home/aoplisti/.local/lib/python3.9/site-packages/numpy/__init__.py", line 311, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'asscalar'
```

**UPDATE**: Seems like the problem is actually conflicting versions of `astropy` and `numpy`. But for the installation of the package definite version numbers should be included, so it automatically installs the right ones (in a virtualenv for instance), see [issue 9](https://github.com/oimodeler/oimodeler/issues/9#issue-1463185166)

**Comment by MBSck** [comment]
Problem originated from colliding versions of dependencies, see update

**Comment by MBSck** [comment]
Problem originated from colliding versions of dependencies, see update
